### ISSUE TITLE
The Roadmap to Specta 1.0

### ISSUE THREAD

**Issue by orta** [specta/specta#125]
Hello there, I have a lot of Specta/Expecta Code out in the wild, I think its a solid, mature and feature complete library. Since Swift came out it _feels_ like it hasn’t been getting the same attention that it used to have. Which I can understand completely, but I'm not going to migrate tens of projects and thousands of tests to Quick/Nimble anytime soon, nor do I want to change the default for a `pod lib create` from Specta yet.

So what I propose is that I request maintainership, and will work on the following to get a stable 1.0 release of Specta/Expecta with a TODO list of:

- [x] Fix OCMock 3 support https://github.com/specta/specta/pull/86
- [x] Get TravisCI working ~~https://github.com/specta/specta/pull/81~~ #126
- [x] Merge the template changes https://github.com/specta/specta/pull/66
- [x] Get it working within a framework for CocoaPods 0.36 support
- [x] Make it only support XCTest
- [x] ~~Swap the `spt_it_` methods with `it` and offer a backwards compatibility flag if anyone uses the verbose modes so that frameworks work with terse syntax by default~~
- [x] Get a new stable release on CocoaPods, so that this isn't needed https://github.com/specta/specta/pull/121

I'm not interested in making major changes ( ARC ) or even really adding features, it's does a great job as it is right now. Just adding some spit shine and trying to get it ready to last the next few years. It's essentially just wrapping up pull requests, cleaning loose ends and tying it together.

I looked through the Expecta PRs, and issues, and there's nothing quite as pressing over there IMO, but there's a bunch of low hanging fruit there too, and some documentation work that could go towards a 1.0 release.

**Comment by modocache** [comment]
I think this is a great initiative! :100: 

I'd love to help review PRs, and I think #103 deserves some attention. I'll try to submit a PR to fix that issue--although if someone else beats me to the punch, no hard feelings! :stuck_out_tongue_closed_eyes:

**Comment by tonyarnold** [comment]
I could get behind this push — I was considering switching my projects over to XCTest directly (and to a degree, I have) but I would prefer to keep using Specta/Expecta for the foreseeable future. 

I'm happy to tackle the framework-related changes.

**Comment by paweldudek** [comment]
Awesome idea. I'll happily contribute to this cause! I'll try to do some work on this next week. I can take TravisCI, the `_spt_it` thing and switch to XCTest only, in this order. 

If anyone wants to grab any of these - please do let me know!

**Comment by orta** [comment]
I, conveniently, have the power to add people to push podspecs, currently on Peter / Blake can push, would anyone else (who is in the org) want adding?

**Comment by robb** [comment]
That's a long con if I've ever seen one

**Comment by orta** [comment]
Hah totally was worth it. I added you for daring to speak up. 

I tested running Specta as a framework, it works as expected, so I'm removing the `_spt_it` to `it` out, that is a requirement for Swift support, but swift support should be outside of the scope of cleanup IMO. 

![screen shot 2015-02-07 at 2 35 55 pm](https://cloud.githubusercontent.com/assets/49038/6093671/b63dbbd0-aed6-11e4-89ec-3366f310cca2.png)

**Comment by tonyarnold** [comment]
> I'm happy to tackle the framework-related changes. 

Which @petejkim already took care of in his earlier 0.3-wip branch. Man I miss the forest for the trees sometimes!

**Comment by paweldudek** [comment]
@orta I've initially thought that

> Make it only support XCTest

means that there's some OCUnit support still out there, but I can find any. Could you shed some light on what you mean by that?

**Comment by orta** [comment]
> means that there's some OCUnit support still out there, but I can find any. Could you shed some light on what you mean by that?

This might be more Expecta things also! I'll tick it.

**Comment by orta** [comment]
Alright, I'm closing this issue. Looks like @paweldudek did most of the code work, thanks :tada: !
Once Expecta has caught up I'll tag a `1.0.0` release to coincide with that. Then maybe take a look at the potential for a Swift Specta separate lib, and rely on swift matcher libs.

**Comment by paweldudek** [comment]
:tada: Yaay! Thanks @orta for doing the hard work on issues/PR! :balloon: Happy to see Specta back on track!
